debug: true

spring:
    datasource:
        url: jdbc:mysql://172.16.2.239:3306/db_zqq?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 12345678

    data:
        mongodb:
            uri: mongodb://192.168.254.117:27017,192.168.254.118:27017
            Database: core-test

es:
    servers: 10.2.1.174:9300;10.2.1.176:9300;10.2.1.177:9300
    cluster:
        name: dcq

nature:
    messagequeue:
        host: wwmq.dgg.net
        username: zhiqianqiu
        password: zhiqianqiu
        vhost: /
        port: 35672

server:
    port: 18577

app:
    user:
        access:
            event: UserAccessEvent.Immediate.LOCAL

seo:
    api:
      url: http://api.zhiqianqiu.com
    upload:
        path:
            root: /opt/zqq/root
        host:
            add: 192.168.254.166
            port: 22
            user: dgg
            password: whitedgg
    mount:
        http:
            path: https://www.zhiqianqiu.com/seo              #静态文件挂载目录
    sitemap:
        build:
            host: 192.168.254.166
            port: 22
            user: dgg
            passwd: whitedgg
            root: /opt/zqq/root/sitemap
            mount:
                path: https://www.zhiqianqiu.com/map          #SiteMap URL SET挂载目录
            segment: 20000
        time:
            schedule: 0 0 23 * * *
    robots:
        host: 192.168.254.166
        port: 22
        user: dgg
        passwd: whitedgg
        root: /opt/zqq/root/sitemap
        mount:
            path: https://www.zhiqianqiu.com/sitemap.xml     #robots定认的sitemap文件位置